#!/bin/bash
# Straight forward script that lists all your git branch with the age prepended at the start.

for k in `git branch|sed s/^..//`;do
    echo -e `git log -1 --pretty=format:"%Cgreen%cr%Creset" "$k"`\\t"$k";
done |sort
